### ISSUE TITLE
rlib 404

### ISSUE THREAD

**Issue by dimmuboy** [recolic/gnome-keyring-yubikey-unlock#1]
What should be in `src/lib/rlib` because current [path](https://github.com/recolic/rlib/tree/12a6021287bf8f9a6adcf83f944a273d57a2f9d3) returns git error page?

**Comment by recolic** [comment]
It should be https://github.com/recolic/rlib

Maybe there's a broken git submodule reference. I'll fix this today. 

### Update:
there would be a compilation error, since rlib has been updated. will fix this today.

**Comment by recolic** [comment]
fixed. let me know if there's any error.
