### ISSUE TITLE
Secret service operation failed

### ISSUE THREAD

**Issue by Snuggle** [recolic/gnome-keyring-yubikey-unlock#11]
Hello! I've been trying to use this script but I keep running into this error.

```
❯ ./unlock_keyrings.sh ~/Desktop/help
gpg: encrypted with cv25519 key, ID FA1E571A026F9FCA, created 2022-07-12
      "Snuggle <user@domain>"
** Message: 01:24:42.776: secret service operation failed: Type of message, ?(o(oayay))?, does not match expected type ?(o(oayays))?
```

When I try to use the debug command I get:
```
❯ echo "login:p" | bin/unlock_keyrings --secret-file -
** Message: 01:29:08.186: secret service operation failed: Type of message, ?(o(oayay))?, does not match expected type ?(o(oayays))?
[Mon Jul 11 01:29:08 2022|ERROR] line 0: Working on keyring `login`: GNOME_KEYRING_RESULT_IO_ERROR.
```

From checking, it does seem like my login keyring is indeed `login` as I use GNOME, so I'm not entirely sure where this might be going wrong. gnome-keyring version `42.1` libgnome-keyring version `2.32.0`

**Comment by recolic** [comment]
Hi. What distro are you using? It might help me to reproduce your issue.

**Comment by Snuggle** [comment]
> Hi. What distro are you using? It might help me to reproduce your issue.

Hello! I am on NixOS 22.05 (Quokka / stable branch) with GNOME 42.2. gnome-keyring version `42.1` libgnome-keyring version `2.32.0`

**Comment by recolic** [comment]
I did some investigation. 
libgnome-keyring 2.32.0 is providing `libgnome-keyring.so.0.1.1`, but Gnome needs `libgnome-keyring.so.0.2.0`. There is a dbus interface mismatch between libgnome-keyring and gnome. 

You need to get a newer version of libgnome-keyring (archlinux is using libgnome-keyring-dev 3.12.0), and link the program against the newer `so`. it will work fine.

**Comment by recolic** [comment]
Mark as resolved since it's not caused by this program. Upgrade your libgnome-keyring.so

**Comment by recolic** [comment]
Also added this issue to the FAQ section. Thanks for your report.
