### ISSUE TITLE
Doesn't unlock the keyring. `gpg: DBG: ignoring gpg-agent inquiry 'CONFIRM 1`

### ISSUE THREAD

**Issue by proninyaroslav** [recolic/gnome-keyring-yubikey-unlock#13]
I tried to set up an unlock on Fedore 39 (I use Nitrokey instead of Yubikey), but I can't unlock the keyring. After decrypting the secret, I get a bunch of messages in the log, every second, even if I run the script manually:

```
gpg: DBG: ignoring gpg-agent inquiry 'CONFIRM 1'
gpg: DBG: ignoring gpg-agent inquiry 'CONFIRM 1'
gpg: DBG: ignoring gpg-agent inquiry 'CONFIRM 1'
gpg: DBG: ignoring gpg-agent inquiry 'CONFIRM 1'
gpg: DBG: ignoring gpg-agent inquiry 'CONFIRM 1'
gpg: DBG: ignoring gpg-agent inquiry 'CONFIRM 1'
gpg: DBG: ignoring gpg-agent inquiry 'CONFIRM 1'
gpg: DBG: ignoring gpg-agent inquiry 'CONFIRM 1'
...
```

At the same time, the system still asks me to enter the keyring password.

**Comment by recolic** [comment]
Hi. Sorry I missed the notification email.
Are you still hitting the same problem? Let me know if it still reproduces.

**Comment by proninyaroslav** [comment]
@recolic 
I tried this last time in December and it didn't work.

**Comment by recolic** [comment]
Hi. Could you try `gpg --decrypt "Your_secret_file" ` and see if your gpg smartcard works?

It looks like a gpg problem.

Mar 26, 2024 01:42:05 Yaroslav Pronin ***@***.***>:

**Comment by recolic** [comment]
This issue looks like a GnuPG problem, unrelated to `gnome-keyring-yubikey-unlock` repo.
Let me know if you still need help.

If no update, I'm going to close it in the next few weeks.
