### ISSUE TITLE
Add a .desktop file for autostart

### ISSUE THREAD

**Issue by danyeaw** [recolic/gnome-keyring-yubikey-unlock#9]
It would help others automate this a little more if we included a desktop file for autostart when logging in to a freedesktop environment.

`$ nano ~/.config/autostart/net.recolic.gnome-keyring-yubikey-unlock.desktop`

Add the following to the file, replacing YOUR_USER with your username:

```
[Desktop Entry]
Type=Application
Exec=/home/YOUR_USER/Projects/gnome-keyring-yubikey-unlock/unlock_keyrings.sh /home/YOUR_USER/.gnupg/gnome_keyring_yubikey_secret
Hidden=false
X-GNOME-Autostart-enabled=true
Name=GNOME Keyring Yubikey Unlock
Comment=Unlocks the GNOME Login Keyring without password
```

**Comment by recolic** [comment]
Looks great. Just keep it easy to use, and PR is welcomed.

Jan 25, 2022 10:24:16 Dan Yeaw ***@***.***>:

**Comment by recolic** [comment]
Hi. 
I have modified <https://git.recolic.net/root/gnome-keyring-yubikey-unlock/-/blob/master/doc/how-to-gnome-autostart.md> to add some guide for autostarting with `.desktop` files. Could you check if it solves this issue?

**Comment by danyeaw** [comment]
Yup, that looks good to me, thanks!
